---
- name: Configure landscape_client
  hosts: all
  gather_facts: false
  vars_files:
    - group_vars/client_var.yml

  tasks:
    - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
    - name: Construct cert path
      set_fact:
        ssl_cert_file: "/etc/ssl/certs/{{ landscape_server }}.crt"
        temp_cert_local: "/tmp/{{ landscape_server }}.crt"

    - name: Fetch SSL certificate from landscape_server
      ansible.builtin.shell: |
        scp -o StrictHostKeyChecking=no {{ landscape_server }}:{{ ssl_cert_file }} {{ temp_cert_local }}
      delegate_to: localhost

    - name: Copy SSL cert to client
      ansible.builtin.copy:
        src: "{{ temp_cert_local }}"
        dest: /etc/landscape/server.crt
        owner: root
        group: root
        mode: '0644'
      delegate_to: "{{ landscape_client_ip }}"

    - name: Run landscape-config on client
      ansible.builtin.shell: |
        sudo landscape-config --silent \
          --account-name="${LANDSCAPE_ACCOUNT_NAME}" \
          --computer-title="${LANDSCAPE_COMPUTER_TITLE}" \
          --tags="" \
          --script-users='nobody,landscape,root' \
          --ping-url="http://${LANDSCAPE_FQDN}/ping" \
          --url="https://${LANDSCAPE_FQDN}/message-system" \
          --ssl-public-key=/etc/landscape/server.crt
      environment:
        LANDSCAPE_ACCOUNT_NAME: "{{ lookup('env', 'LANDSCAPE_ACCOUNT_NAME') }}"
        LANDSCAPE_COMPUTER_TITLE: "{{ lookup('env', 'LANDSCAPE_COMPUTER_TITLE') }}"
        LANDSCAPE_FQDN: "{{ lookup('env', 'LANDSCAPE_FQDN') }}"
      delegate_to: "{{ landscape_client_ip }}"
