---
- name: Configure landscape_client
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - group_vars/client_var.yml

  tasks: 
    - name: Ensure landscape-client is installed
      apt:
        name: landscape-client
        state: present
        update_cache: yes

    - name: Run landscape-config on client
      ansible.builtin.shell: |
        sudo landscape-config --silent \
          --account-name="${LANDSCAPE_ACCOUNT_NAME}" \
          --computer-title="${LANDSCAPE_COMPUTER_TITLE}" \
          --tags="" \
          --script-users='nobody,landscape,root' \
          --ping-url="http://${LANDSCAPE_FQDN}/ping" \
          --url="https://${LANDSCAPE_FQDN}/message-system" \
          --ssl-public-key=/etc/landscape/landscape.crt
      environment:
        LANDSCAPE_ACCOUNT_NAME: "{{ lookup('env', 'LANDSCAPE_ACCOUNT_NAME') }}"
        LANDSCAPE_COMPUTER_TITLE: "{{ lookup('env', 'LANDSCAPE_COMPUTER_TITLE') }}"
        LANDSCAPE_FQDN: "{{ lookup('env', 'LANDSCAPE_FQDN') }}"
      delegate_to: "{{ landscape_client_ip }}"
