name: 'Landscape Server Provision Workflow'
    
on:
  workflow_dispatch:
  
permissions:
  actions: write
  contents: write

jobs:
  setup-landscape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update landscape_hostname and landscape_ip in global variables
        run: |
          # Use sed to update the YAML values
          sed -i "s|^landscape_hostname:.*|landscape_hostname: ${{ vars.EC2_PUBLIC_DNS }}|" ansible-landscape/group_vars/all.yml
          sed -i "s|^landscape_ip:.*|landscape_ip: ${{ vars.EC2_PUBLIC_IP }}|" ansible-landscape/group_vars/all.yml
          sed -i "s|^192.168.1.4*|${{ vars.EC2_PUBLIC_IP }}|" ansible-landscape/inventory/hosts

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add target host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible-landscape/inventory/hosts ansible-landscape/site.yml


    
