name: 'Landscape Client Ansible Provision Workflow'
    
on:
  workflow_dispatch:
  
permissions:
  actions: write
  contents: write

jobs:
  setup-landscape-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update landscape_hostname and landscape_ip in global variables
        run: |
          LANDSCAPE_CLIENT_HOSTNAME="${{ vars.CLIENT_PUBLIC_DNS }}"
          LANDSCAPE_CLIENT_IP="${{ vars.CLIENT_PUBLIC_IP }}"
          LANDSCAPE_SERVER="${{ vars.EC2_PUBLIC_IP }}"

          echo "landscape_client_hostname: $LANDSCAPE_CLIENT_HOSTNAME" >> ansible-landscape/group_vars/client_var.yml
          echo "landscape_client_ip: $LANDSCAPE_CLIENT_IP" >> ansible-landscape/group_vars/client_var.yml
          echo "landscape_server: $LANDSCAPE_SERVER" >> ansible-landscape/group_vars/client_var.yml
          echo "$LANDSCAPE_CLIENT_IP ansible_user=ansible" >> ansible-landscape/inventory/client

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add target host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.CLIENT_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Install landscape client
        run: |
            sudo apt update && sudo apt install -y landscape-client
            

      - name: Configure Client
        run: |
          export LANDSCAPE_ACCOUNT_NAME=standalone
          export LANDSCAPE_FQDN=${{ vars.CLIENT_PUBLIC_IP }}
          export LANDSCAPE_COMPUTER_TITLE=${{ vars.CLIENT_PUBLIC_DNS }}
          ansible-playbook -i ansible-landscape/inventory/client ansible-landscape/client_setup.yml
          
