name: 'Ansible Provision Workflow'
    
on:
  workflow_dispatch:
  
permissions:
  actions: write
  contents: write

jobs:
  use-ec2-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Use EC2 Public IP
        run: echo "The EC2 IP is ${{ vars.EC2_PUBLIC_IP }}"

    