name: 'Ansible Provision Workflow'
    
on:
  workflow_dispatch:
  
permissions:
  actions: write
  contents: write

jobs:
  use-ec2-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Use EC2 Public IP
        run: echo "The EC2 IP is ${{ vars.EC2_PUBLIC_IP }}"

      - name: Use EC2 DNS
        run: echo "The EC2 DNS is ${{ vars.EC2_PUBLIC_DNS }}"

      - name: Update landscape_hostname and landscape_ip in all.yml
        run: |
          ls -l ~/
          pwd
          # Use sed to update the YAML values
          sed -i "s|^landscape_hostname:.*|landscape_hostname: ${{ vars.EC2_PUBLIC_DNS }}|" ansible-landscape/group_vars/all.yml
          sed -i "s|^landscape_ip:.*|landscape_ip: ${{ vars.EC2_PUBLIC_IP }}|" ansible-landscape/group_vars/all.yml

          echo "Updated group_vars/all.yml:"
          cat ansible-landscape/group_vars/all.yml
          ls -l ansible-landscape/
          ls -l group_vars/*


    
