name: 'Terraform Destroy'
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'us-east-1'
    TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-terraform-create:
    name: Check "Terraform Create Workflow" Success
    runs-on: ubuntu-latest
    steps:
      - name: Check last successful run of "Terraform Create Workflow"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking last successful run of 'Terraform Create Workflow'"
          gh run list \
            --repo "${{ github.repository }}" \
            --workflow="Terraform Create Workflow" \
            --limit 1 \
            --json status,conclusion \
            --jq '.[0] | select(.status == "completed" and .conclusion == "success")' || {
            echo "❌ Last run of Terraform Create Workflow did not succeed."
            exit 1
            }

  terraform_validate:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    needs: check-terraform-create
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        
      - name: Terraform fmt
        run: terraform fmt
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

  terraform_destroy_plan:
    name: 'Terraform Destroy Plan'
    runs-on: ubuntu-latest
    needs: terraform_validate  # Ensure this job runs after the init job
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy Plan
        run:  terraform plan -destroy -input=false
        working-directory: ./terraform

  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform_destroy_plan
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -destroy
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        working-directory: ./terraform
