name: 'Terraform Create Workflow'
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'us-east-1'
    TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}

on:
  workflow_dispatch:
  #push:
  #  branches: 
  #    - main

permissions:
  contents: read

jobs:
  terraform_validate:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        
      - name: Terraform fmt
        run: terraform fmt
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: terraform_validate  # Ensure this job runs after the init job
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform_plan  # Ensure this job runs after the plan job
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
